<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NumberFourAirObserverSchool extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('comm')->insert([
            [
        'user_id' => 1,
        'rank' => 'CIVILIAN PILOT',
        'name' => 'ROBERT WILFRED REAIN',
        'picture' => '',
        'info' => 'Killed following a mid-air collision during training exercises.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '2 September 1941',
        'aircraft' => 'Anson 6141',
        'incident' => '',
        'location' => '',
        'details' => 'Anson aircraft 6141 and 6146 collided. Reain died in the crash.',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'CIVILIAN PILOT',
        'name' => 'OSCAR A. LUTKEN',
        'picture' => '',
        'info' => 'Died of injuries following a mid-air collision during training exercises.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '2 September 1941',
        'aircraft' => 'Anson 6141',
        'incident' => '',
        'location' => '',
        'details' => 'Anson aircraft 6141 and 6146 collided. Lutken died the day after the crash',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'CIVILIAN PILOT',
        'name' => 'DONALD GRAY JONES',
        'picture' => '',
        'info' => 'Killed when his aircraft crashed during training.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '4 August 1942',
        'aircraft' => 'Anson 6839',
        'incident' => '',
        'location' => 'Kintore, Ontario',
        'details' => 'Aircraft crashed during training flight. Two student navigators and one wireless air gunner bailed out before impact',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'PILOT OFFICER',
        'name' => 'FREDERICK ALFRED GRIFFIN',
        'picture' => '',
        'info' => 'Killed in a crash during a night navigation exercise.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '3 November 1942',
        'aircraft' => 'Anson 6341',
        'incident' => '',
        'location' => 'Swamp southeast of Dorchester Station, Ontario',
        'details' => 'Aircraft crashed during a night navigation exercise',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'LEADING AIRCRAFTMAN',
        'name' => 'SIDNEY ACKER',
        'picture' => '',
        'info' => 'Killed in a crash during a night navigation exercise.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '3 November 1942',
        'aircraft' => 'Anson 6341',
        'incident' => '',
        'location' => '',
        'details' => 'Aircraft crashed during a night navigation exercise.',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'CIVILIAN PILOT',
        'name' => 'G.H. Rockett',
        'picture' => '',
        'info' => 'Killed in a crash during a night navigation exercise.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '3 November 1942',
        'aircraft' => 'Anson 6341',
        'incident' => '',
        'location' => '',
        'details' => 'Aircraft crashed during a night navigation exercise.',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'LEADING AIRCRAFTMAN',
        'name' => 'JEREMIAH WREN QUINLAN',
        'picture' => '',
        'info' => 'Died of injuries sustained in a training crash.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '3 November 1942',
        'aircraft' => 'Anson 6341',
        'incident' => '',
        'location' => '',
        'details' => 'Survived initial crash but later died of injuries in hospital.',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'LEADING AIRCRAFTMAN',
        'name' => 'KENNETH GERALD SPOONER, GC',
        'picture' => '',
        'info' => 'Killed when Anson 7064 plunged into Lake Erie during training.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '14 May 1943',
        'aircraft' => 'Anson 7064',
        'incident' => '',
        'location' => 'Lake Erie',
        'details' => 'Took control after pilot lost consciousness and ordered crew to abandon aircraft. Remained at controls before the aircraft crashed into Lake Erie. Awarded the George Cross on 1 January 1944.',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'SERGEANT',
        'name' => 'DANA ANTHONY NELSON',
        'picture' => '',
        'info' => 'Killed when Anson 7064 plunged into Lake Erie during training.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '14 May 1943',
        'aircraft' => 'Anson 7064',
        'incident' => '',
        'location' => '',
        'details' => 'Pilot lost consciousness during flight. Aircraft crashed into Lake Erie.',
        'created_at' => now(),
        'updated_at' => now(),
            ],
            [
        'user_id' => 1,
        'rank' => 'SERGEANT (WIRELESS OPERATOR AIR GUNNER)',
        'name' => 'WILLIAM JOHN BROWN',
        'picture' => '',
        'info' => 'Killed after abandoning the aircraft during a training emergency over Lake Erie.',
        'unit' => 'No. 4 Air Observer School',
        'date' => '14 May 1943',
        'aircraft' => 'Anson 7064',
        'incident' => '',
        'location' => '',
        'details' => 'Bailed out over Lake Erie but did not survive descent.',
        'created_at' => now(),
        'updated_at' => now(),
            ],
        ]);
    }
}
